import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./UI/Navbar";
import Footer from "./UI/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh] w-[100vw]`}
			>
				<Navbar />
				<main className="h-[90vh] w-[100vw] flex items-center gap-1 my-[1vh]">
					<div className="h-[91vh] w-[10vw] border-2 border-grey-500 mx-1">
						G
					</div>
					{children}
					<div className="h-[91vh] w-[10vw] border-2 border-grey-500 mx-1">
						D
					</div>
				</main>
				<Footer />
			</body>
		</html>
	);
}
